{% set name = "dsm2dtm" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

# source:
#   git_url: https://github.com/seedlit/{{ name }}.git
source:
  # Relative path to the parent directory.
  # ref: https://stackoverflow.com/a/61810510
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - git
    - python
    - pip
    - setuptools
  host:
    - pip
    - python
  run:
    - python
    - gdal >=3.0.*
    - rasterio
    - numpy

# test:
#   imports:
#     - dsm2dtm

about:
  home: https://github.com/seedlit/dsm2dtm
  license: BSD
  license_family: BSD
  summary: Generates DTM (Digital Terrain Model) from DSM (Digital Surface Model).
