#!/usr/bin/env python3
"""Build script for QGIS plugin packaging.

This script:
1. Cleans previous build artifacts
2. Vendors the dsm2dtm library into the plugin (rename to dsm2dtm_core)
3. Creates a distributable ZIP file

Usage:
    python qgis_plugin/scripts/build_plugin.py            # vendor + build zip
    python qgis_plugin/scripts/build_plugin.py --check    # exit 1 if vendored copy is out of sync
"""

import argparse
import filecmp
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

# Paths
QGIS_PLUGIN_ROOT = Path(__file__).parent.parent  # qgis_plugin/
PROJECT_ROOT = QGIS_PLUGIN_ROOT.parent  # dsm2dtm/
SRC_LIB = PROJECT_ROOT / "src" / "dsm2dtm"
PLUGIN_DIR = QGIS_PLUGIN_ROOT / "dsm2dtm"
EXT_LIBS = PLUGIN_DIR / "ext_libs"
METADATA_FILE = PLUGIN_DIR / "metadata.txt"
PYPROJECT_FILE = PROJECT_ROOT / "pyproject.toml"
OUTPUT_DIR = QGIS_PLUGIN_ROOT / "dist"
OUTPUT_ZIP = OUTPUT_DIR / "dsm2dtm_qgis_plugin.zip"


def clean():
    """Remove previous build artifacts."""
    if OUTPUT_ZIP.exists():
        OUTPUT_ZIP.unlink()
        print(f"✓ Removed old {OUTPUT_ZIP}")


def _read_pyproject_version() -> str:
    """Single source of truth for the plugin version: pyproject.toml's [project].version."""
    text = PYPROJECT_FILE.read_text()
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, flags=re.MULTILINE)
    if match is None:
        raise RuntimeError(f"Could not find version in {PYPROJECT_FILE}")
    return match.group(1)


def sync_metadata_version() -> None:
    """Rewrite the metadata.txt version line so it matches pyproject.toml."""
    pyproject_version = _read_pyproject_version()
    text = METADATA_FILE.read_text()
    new_text, n = re.subn(
        r"^version\s*=.*$",
        f"version={pyproject_version}",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if n == 0:
        raise RuntimeError(f"Could not find version line in {METADATA_FILE}")
    if new_text != text:
        METADATA_FILE.write_text(new_text)
        print(f"✓ Synced {METADATA_FILE.name} version → {pyproject_version}")
    else:
        print(f"✓ {METADATA_FILE.name} version already {pyproject_version}")


# Only QGIS-safe modules get vendored. `core.py` imports rasterio and `__init__.py`
# imports from core, neither of which works in stock QGIS. The plugin's own
# processing_algorithm.py owns I/O and orchestration.
VENDORED_MODULES = ("algorithm.py", "constants.py", "utm_utils.py")

_VENDORED_INIT = '''"""Vendored subset of the dsm2dtm library for the QGIS plugin.

Only the pure numpy/scipy modules are bundled — the QGIS plugin owns its own
raster I/O via osgeo.gdal because rasterio is not part of standard QGIS Python.
This file is generated by qgis_plugin/scripts/build_plugin.py — do not edit by hand.
"""
'''


def _vendor_into(dest: Path) -> None:
    """Copy the QGIS-safe subset of SRC_LIB to `dest` with patched imports."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    for module_name in VENDORED_MODULES:
        src_path = SRC_LIB / module_name
        if not src_path.exists():
            raise FileNotFoundError(f"Expected vendored module not found: {src_path}")
        content = src_path.read_text()
        patched = content.replace("from dsm2dtm.", "from dsm2dtm_core.")
        patched = patched.replace("import dsm2dtm.", "import dsm2dtm_core.")
        (dest / module_name).write_text(patched)

    (dest / "__init__.py").write_text(_VENDORED_INIT)


def vendor_library():
    """Copy dsm2dtm source into ext_libs for vendoring.

    Note: We rename to 'dsm2dtm_core' to avoid naming conflict with the plugin package.
    """
    dest = EXT_LIBS / "dsm2dtm_core"
    _vendor_into(dest)
    print(f"✓ Vendored dsm2dtm as dsm2dtm_core to {dest}")


def check_vendored_in_sync() -> int:
    """Re-vendor into a temp dir and diff against the committed copy. Returns 0 if in sync, 1 otherwise."""
    committed = EXT_LIBS / "dsm2dtm_core"
    if not committed.exists():
        print(f"✗ Drift check: vendored copy missing at {committed}")
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "dsm2dtm_core"
        _vendor_into(fresh)
        diff = filecmp.dircmp(fresh, committed)
        differences = []

        def collect(d: filecmp.dircmp, prefix: str = "") -> None:
            for name in d.left_only:
                differences.append(f"missing in committed: {prefix}{name}")
            for name in d.right_only:
                differences.append(f"unexpected in committed: {prefix}{name}")
            for name in d.diff_files:
                differences.append(f"content mismatch: {prefix}{name}")
            for sub_name, sub in d.subdirs.items():
                collect(sub, prefix=f"{prefix}{sub_name}/")

        collect(diff)
        if differences:
            print("✗ Vendored copy is out of sync with src/dsm2dtm/:")
            for d in differences:
                print(f"  - {d}")
            print("Run `python qgis_plugin/scripts/build_plugin.py` to refresh.")
            return 1
    print("✓ Vendored copy matches src/dsm2dtm/")
    return 0


def create_zip():
    """Create distributable ZIP file for QGIS plugin manager."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(OUTPUT_ZIP, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add plugin files
        for file in PLUGIN_DIR.rglob("*"):
            if file.is_file() and "__pycache__" not in str(file):
                # Archive path should be dsm2dtm/... (plugin folder name)
                arcname = file.relative_to(QGIS_PLUGIN_ROOT)
                zf.write(file, arcname)

        # Add LICENSE file from project root
        license_file = PROJECT_ROOT / "LICENSE"
        if license_file.exists():
            # Place LICENSE inside the dsm2dtm folder in the zip
            zf.write(license_file, "dsm2dtm/LICENSE")
            print("✓ Added LICENSE")
        else:
            print("! Warning: LICENSE file not found in project root")

    print(f"✓ Created {OUTPUT_ZIP}")

    # Print zip contents for verification
    print("\nZIP contents:")
    with zipfile.ZipFile(OUTPUT_ZIP, "r") as zf:
        for name in sorted(zf.namelist())[:20]:
            print(f"  {name}")
        if len(zf.namelist()) > 20:
            print(f"  ... and {len(zf.namelist()) - 20} more files")


def main():
    """Main build entry point."""
    parser = argparse.ArgumentParser(description="Build the dsm2dtm QGIS plugin ZIP.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed vendored copy matches src/dsm2dtm/ and exit. Does not build.",
    )
    args = parser.parse_args()

    if not SRC_LIB.exists():
        print(f"✗ Error: Source library not found at {SRC_LIB}")
        return 1
    if not PLUGIN_DIR.exists():
        print(f"✗ Error: Plugin directory not found at {PLUGIN_DIR}")
        return 1

    if args.check:
        return check_vendored_in_sync()

    print("=" * 50)
    print("Building QGIS Plugin for dsm2dtm")
    print("=" * 50)
    print()

    clean()
    sync_metadata_version()
    vendor_library()
    create_zip()

    print()
    print("=" * 50)
    print("Build complete!")
    print("=" * 50)
    print()
    print("To install:")
    print("1. Open QGIS")
    print("2. Go to: Plugins → Manage and Install Plugins → Install from ZIP")
    print(f"3. Select: {OUTPUT_ZIP}")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
