"""Vendored subset of the dsm2dtm library for the QGIS plugin.

Only the pure numpy/scipy modules are bundled — the QGIS plugin owns its own
raster I/O via osgeo.gdal because rasterio is not part of standard QGIS Python.
This file is generated by qgis_plugin/scripts/build_plugin.py — do not edit by hand.
"""
